export const DATE = '2026-09-06';
export const notes = [
  {
    id: 'outage-decision', slug: 'security-system-outage', type: 'Public-source analysis', author: 'Shannon Brown', visibility: 'public', published: DATE, reviewed: DATE,
    title: 'When a security-system outage becomes a business-risk decision',
    summary: 'The critical question is what the business can safely continue while its picture is incomplete.',
    judgment: 'Treat a loss of security visibility as a business-risk decision when the remaining controls can no longer support the activity being protected.',
    assumptions: 'A fictional organization has a partial monitoring outage; no immediate life-safety emergency is established.',
    alternatives: 'Continue normally if independent controls preserve the required assurance; suspend activity if the consequence cannot be contained.',
    indicators: 'Independent verification fails, the affected activity becomes more consequential, or a promised compensating control cannot be sustained.',
    references: [{title:'NIST Cybersecurity Framework 2.0, Govern',url:'https://nvlpubs.nist.gov/nistpubs/CSWP/NIST.CSWP.29.pdf'}, {title:'ASIS: Meet the 3 Key Roles Within ESRM',url:'https://www.asisonline.org/security-management-magazine/articles/2023/09/esrm/key-roles-esrm/'}],
    body: `
<h2>The outage is a symptom. The decision concerns exposure.</h2>
<p>A camera-management service becomes unavailable. A technical team investigates. The easy status update is “restoration in progress.” The harder question is whether the activities that depended on that visibility should continue unchanged. That is where a security-system issue becomes a leadership decision: someone must connect the degraded control to a business objective, explain the remaining exposure, and name who can accept it.</p>
<p>Consider a fictional distribution operation with a partial loss of remote video. Local access controls appear operational, but that report has not yet been independently checked. A time-sensitive shipment is due. There is no established evidence of intrusion. These are deliberately synthetic conditions, not a description of an employer event. They create a useful distinction: an unavailable observation channel is neither proof of an attack nor proof that normal operations remain appropriate.</p>
<h2>Start with the activity, then the control</h2>
<p><a href="https://nvlpubs.nist.gov/nistpubs/CSWP/NIST.CSWP.29.pdf">NIST CSF 2.0</a> places cybersecurity risk within organizational context and governance. <a href="https://www.asisonline.org/security-management-magazine/articles/2023/09/esrm/key-roles-esrm/">ASIS’s description of ESRM roles</a> assigns risk ownership to the asset owner, with security advising on the decision. Together, these sources support a useful framing: technical recovery and business authorization are connected responsibilities, with different accountable owners.</p>
<p>My application of that framing is to ask three questions before recommending a posture. What activity is relying on the affected control? Which independent protection still works? What consequence could arise before the next decision point? An outage affecting retrospective footage might permit a different response from one affecting the only means of verifying a consequential live activity. The same system label can conceal very different exposure.</p>
<h2>Make a bounded recommendation</h2>
<p>In the fictional example, I would recommend restricted continuation only after the responsible team verifies the independent controls and the asset owner accepts the defined residual risk. The recommendation should identify the permitted activity, the substitute verification, its owner, and the point at which permission expires. “Increase vigilance” is too vague to establish whether a treatment exists or whether anyone can sustain it.</p>
<p>A bounded decision also protects against quiet scope expansion. Permission for one controlled shipment does not automatically cover every shipment, every entrance, or the next shift. When the operation changes, the reasoning may stop applying. Writing the boundary makes that visible before a temporary arrangement becomes an unexamined operating model.</p>
<h2>The credible alternatives</h2>
<p>Normal continuation is reasonable if independent evidence shows that the unavailable service does not materially weaken the protection required for this activity. Overreacting can create avoidable disruption and consume the capacity needed to recover. At the other end, suspension is reasonable when the consequence of a missed event is severe and no reliable substitute is available. A security leader should present both alternatives fairly, including their operational costs.</p>
<p>Restricted continuation sits between those choices, but it is not automatically the balanced answer. It can be the worst option if the substitute depends on exhausted personnel, ambiguous instructions, or a verification process that only appears independent. The recommendation must survive that challenge rather than receive credit simply for sounding moderate.</p>
<h2>What remains uncertain</h2>
<p>The example does not establish the outage’s cause, the reliability of the reported access controls, the consequence of shipment delay, or the capacity to provide substitute verification. Those unknowns prevent a confident recommendation for a real organization. Confidence is stronger in the decision method than in any particular posture: connect activity to exposure, verify the treatment, assign ownership, and set a review trigger.</p>
<h2>What would change the judgment</h2>
<p>I would revisit continuation if independent verification failed, if the activity became more consequential, or if the substitute control could not be maintained. Restoration is also a trigger, but a successful service restart alone does not prove that the full protective function has recovered. The recovery owner should define the evidence required to return to normal, and the decision owner should close the temporary arrangement explicitly.</p>
<p>The executive update can then be brief and useful: what can continue, on what conditions, who owns the residual risk, and when the decision changes. That is a more actionable result than a technical restoration estimate standing alone.</p>`
  },
  {
    id: 'executive-brief', slug: 'briefing-before-certainty', type: 'Public-source analysis', author: 'Shannon Brown', visibility: 'public', published: DATE, reviewed: DATE,
    title: 'What an executive brief must say before the picture is complete',
    summary: 'Useful uncertainty tells a decision-maker what can be done now—and what evidence would change the call.',
    judgment: 'An incomplete picture can support a sound decision when the brief separates what is observed, what is inferred, and what must be decided before better information arrives.',
    assumptions: 'A decision has a real time constraint and a named owner; the example does not describe a live incident.',
    alternatives: 'Delay the recommendation when the decision is reversible and the next evidence is both timely and consequential.',
    indicators: 'A critical assumption fails, credible contrary reporting arrives, the decision window changes, or the proposed treatment becomes infeasible.',
    references: [{title:'ODNI ICD 203: Analytic Standards (public directive)',url:'https://archive.dni.gov/files/documents/ICD/ICD-203.pdf'}, {title:'NIST Cybersecurity Framework 2.0',url:'https://nvlpubs.nist.gov/nistpubs/CSWP/NIST.CSWP.29.pdf'}],
    body: `
<h2>Lead with the decision that cannot wait</h2>
<p>An executive rarely needs the entire event stream. They need to know whether a consequential choice is approaching, what the team believes, and how strongly the evidence supports that view. A brief that lists every incoming report can be accurate while leaving the reader unable to act. The discipline is to preserve uncertainty without transferring the whole analysis burden to the audience.</p>
<p>My preferred opening names the decision, the relevant time window, and the recommendation. The next sentence identifies the strongest reason for that recommendation and its most important limitation. This is an editorial method for making analysis useful. It is not a claim that every situation should be reduced to two sentences, or that confident presentation compensates for weak evidence.</p>
<h2>Keep three kinds of statement separate</h2>
<p>The public <a href="https://archive.dni.gov/files/documents/ICD/ICD-203.pdf">ODNI Analytic Standards</a> distinguish underlying information from assumptions and judgments, and call for attention to uncertainty and alternatives. I use those principles here as a writing discipline; this is independent professional analysis, without any intelligence-agency affiliation or endorsement.</p>
<p>In a synthetic example, “two independent services stopped reporting within the same interval” is an observation if the timestamps have been checked. “A shared dependency may be involved” is an inference. “The independent fallback remains usable” is an assumption until someone verifies it. Combining all three into “the backup will cover a shared-system failure” hides the least secure part of the argument inside its conclusion.</p>
<p>The separation matters because each statement invites a different action. An observation needs a source and a time. An inference needs reasoning and a competing explanation. An assumption needs an owner who can test it. The brief becomes a small work plan as well as an assessment.</p>
<h2>Explain confidence in ordinary language</h2>
<p>“We have consistent reporting from two independent sources, but have not verified the affected boundary” is more useful than an unexplained confidence score. It tells the reader both why the assessment has weight and where it may fail. I would reserve numerical probabilities for situations with an adequate basis and a clear interpretation. Precision in formatting does not create precision in knowledge.</p>
<p>Confidence should also attach to the right claim. The team may be confident that visibility is impaired while remaining uncertain about cause. It may recommend a temporary restriction with confidence because that action is reversible, even when the cause remains unresolved. A single confidence label for the whole incident obscures these differences.</p>
<h2>Give the alternative a fair hearing</h2>
<p>A useful alternative is an explanation that could change the decision, not a ceremonial paragraph at the end. Could a reporting fault explain the apparent convergence? Could waiting for an independent check avoid an unnecessary interruption? What evidence would distinguish those accounts? Stating the alternative helps the audience challenge the reasoning without needing to reconstruct it.</p>
<p>There are circumstances where waiting is the better recommendation. If the decision remains reversible, exposure stays bounded, and a decisive observation is expected within the available window, acting immediately may create more cost than value. The brief should say why its timing matters. Urgency should come from the decision context, not from the writer’s tone.</p>
<h2>Connect the recommendation to authority</h2>
<p><a href="https://nvlpubs.nist.gov/nistpubs/CSWP/NIST.CSWP.29.pdf">NIST CSF 2.0’s Govern function</a> emphasizes organizational roles and risk-management expectations. In a practical brief, that means naming who decides, who executes the treatment, and who returns with the next assessment. Those responsibilities should not blur merely because a security team assembled the information.</p>
<p>For the synthetic example, a recommendation might permit a limited activity after independent verification, with a named asset owner accepting the remaining exposure. The technical team still owns diagnosis and recovery. The security team still owns the quality of its advice. The brief should make those handoffs easier to execute and easier to revisit.</p>
<h2>Finish with the conditions for changing your mind</h2>
<p>The final line should identify a time or an observable trigger: the fallback fails verification, credible contrary reporting arrives, the scope expands, or the treatment becomes infeasible. These triggers keep a reasonable earlier decision from becoming an unreasonable later one. A review time is useful even when no new information is expected; silence should not silently renew permission.</p>
<p>The underlying assumptions are that a decision has a real time constraint and a named owner. Where either is missing, clarify the problem before optimizing the brief. The aim is not to sound certain before the facts permit it. It is to give accountable people enough structure to act, challenge the judgment, and change course deliberately.</p>`
  }
];

export const caseBody = `
<h2 id="problem">A first hour with imperfect information</h2>
<p>A stream of alarms does not produce a decision by itself. Someone must decide which reports matter, what remains unknown, which activity can continue, and who is accountable for the remaining risk. Hourglass Command explores that problem through a fictional security operation. The intended learner is a practitioner who wants to rehearse a structured decision and then inspect the reasoning behind it.</p>
<p>The project constrains the experience to a manageable training session. It does not attempt to reproduce an employer’s environment or integrate operational systems. Synthetic scenarios let a learner revisit the same situation, compare different choices, and examine consequences without involving real facilities, personnel, or incident data. That boundary is part of the product’s usefulness.</p>
<h2 id="contribution">My contribution and the role of AI</h2>
<p>I set the problem, product direction, and security-operations perspective for this independent portfolio project. The design and software were developed through AI-assisted iteration. The public repository contains the implementation, scenario material, training methodology, and revision history. This distinction matters: the work demonstrates a product I directed and developed with AI assistance, not a claim that I manually authored every line of code or independently validated every training assumption.</p>
<p>My GSOC responsibilities inform the questions the project asks: how to separate facts from assumptions, establish reliable handoffs, explain a recommendation, and keep risk ownership visible. The simulation itself is separate from that professional experience. It does not contain employer playbooks or establish that its scoring predicts workplace performance.</p>
<h2 id="decisions">Three decisions that shape the product</h2>
<h3>01 / Commit a posture, then expose the reasoning</h3>
<p><strong>Implemented choice.</strong> The learner recommends CONTINUE, DEGRADE, or PAUSE, with treatment, rationale, ownership, and residual risk. A plausible alternative is an entirely open-ended narrative exercise. Another is a quiz with a single preselected correct answer. The implementation uses an explicit posture to make the decision inspectable while preserving space for its explanation.</p>
<p><strong>Tradeoff.</strong> A small set of postures reduces ambiguity in the interface, but cannot capture every operational nuance. A DEGRADE choice, for example, is meaningful only when its compensating treatment is credible. The explanation must carry that detail. This comparison describes the present design rationale, not a claim of a documented historical experiment between prototypes.</p>
<p><strong>Evidence and revision trigger.</strong> The live decision panel and core decision rules expose how inputs are represented. Core automated tests check encoded behavior, not whether the behavior is pedagogically sufficient. I would revisit the structure if observed learners consistently need exceptions that the posture model obscures, or if they can earn a strong result with reasoning a practitioner would reject.</p>
<h3>02 / Put the advisor and the asset owner in the same decision</h3>
<p><strong>Implemented choice.</strong> The interface distinguishes a security recommendation from asset-owner risk acceptance. It makes treatment and residual risk part of the workflow. The simpler alternative would let the person operating the simulation make an apparently final business decision without an explicit owner. That would be faster, but would hide an important governance question.</p>
<p><strong>Tradeoff.</strong> Requiring a handoff adds friction. It can feel repetitive once the learner understands the principle. The benefit is that ownership becomes something the learner practices rather than a statement confined to the methodology. The <a href="https://www.asisonline.org/security-management-magazine/articles/2023/09/esrm/key-roles-esrm/">ASIS account of ESRM roles</a> provides the public conceptual basis for that distinction.</p>
<p><strong>Evidence and revision trigger.</strong> The training documentation maps the advisor-to-owner workflow to explicit mechanics. The decision record lets a reviewer inspect what was entered. I would change the interaction if a structured learner review found that people mistake a simulated affirmation for actual executive negotiation, or if the handoff obscures rather than clarifies accountability.</p>
<h3>03 / Make reflection portable and the sensory layer optional</h3>
<p><strong>Implemented choice.</strong> A decision trail and after-action export preserve the session for review. Optional spoken information and a 3D operating picture support the experience. A purely cinematic simulation could emphasize immersion; a text-only worksheet could reduce technical demands. This product combines a working interface with an inspectable record, while keeping its training scope explicit.</p>
<p><strong>Tradeoff.</strong> Rich presentation adds accessibility, memory, and browser-compatibility work. Optional local voice models are especially demanding. The September 2026 first-enable repair introduced quantized model loading, memory-pressure checks, and fallback behavior. That repair is evidence of an engineering constraint, not proof that every device can support the feature.</p>
<p><strong>Evidence and revision trigger.</strong> The source contains dedicated voice-load policy tests, and the revision linked below records the first-enable change. The portfolio never loads the simulation or its voice models in the background. I would simplify the sensory layer further if device testing shows that it competes with reading, makes controls harder to reach, or materially reduces session reliability.</p>
<h2 id="walkthrough">A session you can inspect</h2>
<p>Start with the campaign for a guided progression, or use free play to select a scenario. Read the available reports and establish the common operating picture. Distinguish facts, assumptions, and unknowns before selecting a posture. Record the treatment and reasoning, identify the appropriate owner, and revisit the recommendation as the scenario develops.</p>
<p>The after-action review makes the path through the session visible. It can support discussion about what was known at a particular point, why an action was taken, and what should change next time. The captures below come from the real public application. This written walkthrough remains available if the live application cannot run on your device.</p>
<h2 id="limitations">What the project establishes—and what remains open</h2>
<p>The observable result is a working, publicly inspectable training product. It includes a six-chapter campaign, free play, posture decisions, local progress, and after-action documentation. The repository’s automated checks exercise its implementation. None of that establishes a measured improvement in real-world incident outcomes or proves that its scoring is a validated assessment of leadership ability.</p>
<p>The simulation does not reproduce workforce management, negotiation, executive relationships, stakeholder politics, or the consequences of real operational authority. It is unsuitable as a production incident system or an organizational system of record. All environments and incidents are synthetic. No employer deployment or endorsement is claimed.</p>
<p>The next substantive validation is a facilitated learner review: compare the recorded reasoning with practitioner feedback, observe where users misunderstand ownership, and identify whether presentation helps them notice the relevant facts. That is a question for evaluation, not a result to imply through branding.</p>`;
